name: GravitationalBattle
version: 1.0.0
main: com.br.gravitationalbattle.GravitationalBattle
author: DuduxindevAtualize ogame.java com isso
description: Plugin de mini-game de batalha gravitacional para Minecraft
softdepend: [Multiverse-Core]

commands:
  gravitationalbattle:
    description: Comando principal do Gravitational Battle
    aliases: [gb, gravitationalbattle]
    usage: /gb [help|reload]
  arena:
    description: Gerenciar arenas do Gravitational Battle
    usage: /arena [create|delete|list|setspawn|setlobby|info]
  setlobby:
    description: Define o lobby do Gravitational Battle
    usage: /setlobby
  join:
    description: Entra em um jogo do Gravitational Battle
    usage: /join [arena|random]
  leave:
    description: Sai do jogo atual
    usage: /leave
  spectate:
    description: Assiste um jogo em andamento
    usage: /spectate <arena|jogador>
  stats:
    description: Mostra estatísticas de um jogador
    usage: /stats [jogador]
  abrirloja:
    description: Abre a loja do jogo
    usage: /abrirloja
    aliases: [loja, shop]

permissions:
  gravitationalbattle.admin:
    description: Permite acesso a comandos administrativos
    default: op
  gravitationalbattle.play:
    description: Permite jogar o mini-game
    default: true
  gravitationalbattle.spectate:
    description: Permite assistir jogos
    default: true
  gravitationalbattle.stats:
    description: Permite ver estatísticas de outros jogadores
    default: true
  gravitationalbattle.shop:
    description: Permite abrir a loja do jogo
    default: true