name: GravitationalBattle
version: 1.0.0
main: com.br.gravitationalbattle.GravitationalBattle
api-version: 1.16
depend: [Multiverse-Core]
author: Duduxindev
description: Um minigame de batalha com gravidade alterada

commands:
  gravitationalbattle:
    description: Comando principal do plugin
    usage: /<command> [reload|help]
    aliases: [gb]
    permission: gravitationalbattle.use

  arena:
    description: Gerencia arenas do minigame
    usage: /<command> [create|delete|list|addspawn|tp|setstate]
    permission: gravitationalbattle.admin

  join:
    description: Entra em um jogo
    usage: /<command> [arena]
    permission: gravitationalbattle.join

  leave:
    description: Sai do jogo atual
    usage: /<command>
    permission: gravitationalbattle.join

  setlobby:
    description: Define o lobby principal
    usage: /<command>
    permission: gravitationalbattle.admin

  spectate:
    description: Assiste a um jogo
    usage: /<command> <arena|jogador>
    aliases: [spec]
    permission: gravitationalbattle.spectate

  stats:
    description: Mostra estatísticas de jogadores
    usage: /<command> [jogador]
    permission: gravitationalbattle.stats

permissions:
  gravitationalbattle.use:
    description: Permite usar os comandos básicos do plugin
    default: true

  gravitationalbattle.join:
    description: Permite entrar e sair dos jogos
    default: true

  gravitationalbattle.spectate:
    description: Permite assistir jogos
    default: true

  gravitationalbattle.stats:
    description: Permite ver estatísticas
    default: true

  gravitationalbattle.admin:
    description: Acesso administrativo ao plugin
    default: op
    children:
      gravitationalbattle.use: true
      gravitationalbattle.join: true
      gravitationalbattle.spectate: true
      gravitationalbattle.stats: true