name: GravitationalBattle
version: 1.0.0
main: com.br.gravitationalbattle.GravitationalBattle
api-version: 1.16
description: Um minigame de batalha com gravidade alterada para Bukkit/Spigot
author: Duduxindev
depend: [Multiverse-Core]

commands:
  gravitationalbattle:
    description: Comando principal do plugin
    aliases: [gb]
    usage: /gb [help|reload]
  arena:
    description: Gerencia as arenas do jogo
    usage: /arena [create|delete|list|addspawn|tp|setstate]
    permission: gravitationalbattle.admin
  join:
    description: Entra em uma arena
    usage: /join [arena]
    permission: gravitationalbattle.join
  leave:
    description: Sai da arena atual
    usage: /leave
    permission: gravitationalbattle.leave
  setlobby:
    description: Define o lobby principal do plugin
    usage: /setlobby
    permission: gravitationalbattle.admin.setlobby
  spectate:
    description: Assiste a uma partida
    usage: /spectate <arena|jogador>
    permission: gravitationalbattle.spectate
  stats:
    description: Mostra estatísticas do jogador
    usage: /stats [jogador]
    permission: gravitationalbattle.stats
  admin:
    description: Comandos administrativos
    usage: /admin [forcestart|forceend|reload]
    permission: gravitationalbattle.admin

permissions:
  gravitationalbattle.admin:
    description: Acesso a todos os comandos de administração
    default: op
  gravitationalbattle.admin.forcestart:
    description: Permite iniciar jogos à força
    default: op
    children:
      gravitationalbattle.admin: true
  gravitationalbattle.admin.forceend:
    description: Permite terminar jogos à força
    default: op
    children:
      gravitationalbattle.admin: true
  gravitationalbattle.admin.reload:
    description: Permite recarregar configurações
    default: op
    children:
      gravitationalbattle.admin: true
  gravitationalbattle.admin.setlobby:
    description: Permite definir o lobby principal
    default: op
    children:
      gravitationalbattle.admin: true
  gravitationalbattle.join:
    description: Permite entrar nos jogos
    default: true
  gravitationalbattle.leave:
    description: Permite sair dos jogos
    default: true
  gravitationalbattle.spectate:
    description: Permite assistir jogos
    default: true
  gravitationalbattle.stats:
    description: Permite ver estatísticas
    default: true
  gravitationalbattle.*:
    description: Permite todos os comandos
    default: op
    children:
      gravitationalbattle.admin: true
      gravitationalbattle.join: true
      gravitationalbattle.leave: true
      gravitationalbattle.spectate: true
